security:
  oauth2:
    client:
      clientId: statistics-service
      #clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      clientSecret: 123456
      #accessTokenUri: http://auth-service:5000/uaa/oauth/token
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      #host: account-mongodb
      #host: 127.0.0.1
      #username: user
      #password: 123456
      #database: piggymetrics
      #port: 27017
      uri: mongodb://user:123456@localhost:27017/piggymetrics

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io